### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by Daipu** [Daipu/COBALT#1]
- [x] Count Graph for CoDel
- [x] Instantaneous Throughput of each Flow on a Single graph.
- [x] Cwnd Graphs: COBALT, CoDel, PIE.
- [x] Zoomed in plots on small time intervals to show the dynamic behavior of the algorithm.
- [x]  Plots for the actual number of marks/drops per time interval for COBALT, CoDel, and PIE.
- [x] A file showing the timestamp of each drop.
- [x] Run FQ-CoDel with 100Mbps bandwidth, 20ms RTT, 80ms RTT.
- [x] Repeat experiments after reducing the size of NIC buffer size to 1 packet.

**Comment by mohittahiliani** [comment]
All listed points are completed.

Closing!
